# Basic Site Settings
locale                   : "en-US"
title                    : "Kumar Puran Tripathy"
title_separator          : "-"
name                     : &name "Kumar Puran Tripathy"
description              : &description "Postdoctoral Researcher in Hydrology and Water Resources Engineering"   
url                      : https://ktripa.github.io
baseurl                  : ""
repository               : "ktripa/ktripa.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Kumar Puran Tripathy"
  bio              : "Postdoctoral Researcher | Hydroclimatic Extremes | AI4Science"
  location         : "College Station, Texas"
  employer         : "Texas A&M University"
  email            : "tripathypuranbdk@gmail.com"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=wMA_dkQAAAAJ&hl=en"
  orcid            : "https://orcid.org/0000-0002-2451-0166"
  github           : "ktripa"
  linkedin         : "kumar-p-tripathy-ph-d-91447517a"
  researchgate     : # Add if you have one

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
atom_feed:
  hide                   : false

# Analytics
analytics:
  provider               : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - LICENSE
  - README
  - node_modules
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections - ONLY PUBLICATIONS
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Chicago

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development